const cfg=window.JF_SUPABASE||{};let db=null;if(window.supabase&&cfg.url&&cfg.anonKey)db=window.supabase.createClient(cfg.url,cfg.anonKey);
let products=[],orders=[],settings={title:"JF ESSENTIALS",wa:"",email:""},dragFrom=null;
const $=id=>document.getElementById(id);
function toast(m){const e=$("toast");e.textContent=m;e.classList.add("show");clearTimeout(window._toast);window._toast=setTimeout(()=>e.classList.remove("show"),2400)}
function esc(s){return String(s??"").replace(/[&<>'"]/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[m]))}
async function adminLogin(){if(!db)return toast("Connect Supabase first in supabase-config.js.");const email=$("adminEmail").value.trim(),password=$("adminPassword").value;if(!email||!password)return toast("Enter email and password.");const r=await db.auth.signInWithPassword({email,password});if(r.error)return toast(r.error.message);await boot()}
async function boot(){const u=await db.auth.getUser();const user=u.data.user;if(!user)return;const p=await db.from("profiles").select("role").eq("id",user.id).single();if(p.error||!p.data||p.data.role!=="admin"){await db.auth.signOut();return toast("This account is not an admin.")}$("loginBox").classList.add("hidden");$("adminApp").classList.remove("hidden");await loadData();renderAdmin()}
async function loadData(){const p=await db.from("products").select("*").order("sort_order",{ascending:true});if(p.error)return toast(p.error.message);products=p.data||[];const s=await db.from("store_settings").select("key,value");if(!s.error)(s.data||[]).forEach(x=>settings[x.key]=x.value);const o=await db.from("orders").select("*").order("created_at",{ascending:false});if(!o.error)orders=o.data||[]}
function showTab(id,b){document.querySelectorAll(".admin-tabs button").forEach(x=>x.classList.remove("active"));b.classList.add("active");["productsTab","ordersTab","storeTab"].forEach(x=>$(x).classList.toggle("hidden",x!==id))}
function renderAdmin(){$("titleSetting").value=settings.title||"";$("waSetting").value=settings.wa||"";$("emailSetting").value=settings.email||"";renderAdminProducts();renderOrders()}
function renderAdminProducts(){const box=$("adminProducts");box.innerHTML="";products.forEach((p,i)=>{const d=document.createElement("div");d.className="admin-card";d.draggable=true;d.dataset.i=i;d.ondragstart=()=>{dragFrom=i;d.classList.add("dragging")};d.ondragend=()=>d.classList.remove("dragging");d.ondragover=e=>e.preventDefault();d.ondrop=e=>{e.preventDefault();const to=Number(d.dataset.i);if(dragFrom===null||dragFrom===to)return;const [m]=products.splice(dragFrom,1);products.splice(to,0,m);dragFrom=null;renderAdminProducts();toast("New order selected — SAVE ORDER to publish.")};const imgs=(p.images||[]);d.innerHTML=`<div class="drag-handle">☷ DRAG TO ARRANGE</div><h4>${esc(p.name)}</h4><div class="admin-image-grid">${imgs.map((x,j)=>{const src=typeof x==="string"?x:x.src;return `<div class="admin-image"><img src="${src}" alt=""><button class="remove-image" onclick="removeImage(${i},${j})">×</button></div>`}).join("")}</div><div class="photo-tools"><label>ADD PHOTOS<input type="file" accept="image/*" multiple onchange="uploadImages(${i},this.files)"></label><label>PHOTO COLOUR<select id="photoColor-${i}">${(p.colors||["Black"]).map(c=>`<option>${esc(c)}</option>`).join("")}</select></label></div><label>Name<input value="${esc(p.name)}" onchange="edit(${i},'name',this.value)"></label><div class="two"><label>Category<input value="${esc(p.category||"JF")}" onchange="edit(${i},'category',this.value)"></label><label>Badge<input value="${esc(p.badge||"JF")}" onchange="edit(${i},'badge',this.value)"></label></div><label>Description<textarea onchange="edit(${i},'description',this.value)">${esc(p.description||"")}</textarea><label>Colours — comma separated<input value="${esc((p.colors||[]).join(", "))}" onchange="editColors(${i},this.value)"></label><label>Sizes — comma separated<input value="${esc((p.sizes||[]).join(", "))}" onchange="editSizes(${i},this.value)"></label><div class="price-grid">${(p.sizes||[]).map(s=>`<label>${esc(s)} price<input type="number" value="${Number(p.prices?.[s]??p.price??0)}" onchange='editPrice(${i},${JSON.stringify(s)},this.value)'></label>`).join("")}</div><button class="danger" onclick="deleteProduct(${i})">DELETE PRODUCT</button>`;box.appendChild(d)})}
function edit(i,k,v){products[i][k]=v;persistProduct(i)}
function editColors(i,v){products[i].colors=v.split(",").map(x=>x.trim()).filter(Boolean);persistProduct(i);renderAdminProducts()}
function editSizes(i,v){products[i].sizes=v.split(",").map(x=>x.trim()).filter(Boolean);products[i].prices=products[i].prices||{};products[i].sizes.forEach(s=>{if(products[i].prices[s]==null)products[i].prices[s]=Number(products[i].price||0)});persistProduct(i);renderAdminProducts()}
function editPrice(i,s,v){products[i].prices=products[i].prices||{};products[i].prices[s]=Number(v)||0;persistProduct(i)}
async function persistProduct(i){if(!db)return;const p=products[i];const r=await db.from("products").update({name:p.name,description:p.description,category:p.category,badge:p.badge,colors:p.colors,sizes:p.sizes,prices:p.prices,images:p.images}).eq("id",p.id);if(r.error)toast(r.error.message)}
async function uploadImages(i,files){if(!db)return toast("Connect Supabase first.");const color=$("photoColor-"+i).value;for(const file of Array.from(files||[])){if(!file.type.startsWith("image/"))continue;const safe=file.name.replace(/[^a-zA-Z0-9._-]/g,"_");const path=products[i].id+"/"+Date.now()+"-"+Math.random().toString(36).slice(2)+"-"+safe;const u=await db.storage.from("product-images").upload(path,file,{upsert:false});if(u.error){toast(u.error.message);continue}const url=db.storage.from("product-images").getPublicUrl(path).data.publicUrl;products[i].images=products[i].images||[];products[i].images.push({src:url,color})}await persistProduct(i);renderAdminProducts();toast("Photo(s) added.")}
async function removeImage(i,j){if(!confirm("Remove this photo?"))return;const x=products[i].images[j];if(db&&x&&x.src&&x.src.includes("/product-images/")){const path=decodeURIComponent(x.src.split("/product-images/")[1].split("?")[0]);await db.storage.from("product-images").remove([path])}products[i].images.splice(j,1);await persistProduct(i);renderAdminProducts();toast("Photo removed.")}
async function saveOrder(){if(!db)return toast("Connect Supabase first.");for(let i=0;i<products.length;i++){const r=await db.from("products").update({sort_order:i}).eq("id",products[i].id);if(r.error)return toast(r.error.message)}toast("STORE ORDER PUBLISHED GLOBALLY.")}
async function addProduct(){if(!db)return toast("Connect Supabase first.");const p={id:crypto.randomUUID(),name:"New JF Product",description:"Describe this JF piece.",category:"New",badge:"NEW",colors:["Black"],sizes:["S","M","L","XL","2XL"],prices:{S:500,M:500,L:500,XL:550,"2XL":600},images:[],sort_order:products.length};const r=await db.from("products").insert(p);if(r.error)return toast(r.error.message);products.push(p);renderAdminProducts();toast("Product added.")}
async function deleteProduct(i){if(!confirm("Delete this product?"))return;const p=products[i];const r=await db.from("products").delete().eq("id",p.id);if(r.error)return toast(r.error.message);products.splice(i,1);renderAdminProducts();toast("Product deleted.")}
function renderOrders(){const box=$("adminOrders");box.innerHTML=orders.length?orders.map(o=>`<div class="order-card"><h4>${esc(o.name)} — R${Number(o.total||0).toLocaleString("en-ZA")}</h4><div class="hint">${esc(o.created_at||"")}<br>${esc(o.phone||"")} · ${esc(o.email||"")}<br>${esc(o.address||"")}, ${esc(o.city||"")}, ${esc(o.province||"")}, ${esc(o.country||"")}</div><p>${(o.items||[]).map(x=>`${x.qty}× ${esc(x.name)} (${esc(x.color)}, ${esc(x.size)})`).join("<br>")}</p></div>`).join(""):"<p class='hint'>No orders yet.</p>"}
async function clearOrders(){if(!confirm("Clear all orders?"))return;const r=await db.from("orders").delete().not("id","is",null);if(r.error)return toast(r.error.message);orders=[];renderOrders();toast("Orders cleared.")}
async function saveStore(){settings.title=$("titleSetting").value.trim()||"JF ESSENTIALS";settings.wa=$("waSetting").value.replace(/\D/g,"");settings.email=$("emailSetting").value.trim();for(const key of Object.keys(settings)){const r=await db.from("store_settings").upsert({key,value:settings[key]});if(r.error)return toast(r.error.message)}toast("STORE SETTINGS PUBLISHED GLOBALLY.")}
window.addEventListener("load",async()=>{if(!db)toast("Add Supabase URL + anon key first.");else{const s=await db.auth.getSession();if(s.data.session)boot()}});
