let products=JSON.parse(localStorage.getItem('jf_products'))||[{id:1,name:'JF Signature Hoodie',price:699,image:'',colors:['Black','White'],sizes:['S','M','L','XL']},{id:2,name:'JF Core Tee',price:399,image:'',colors:['Black','White','Gold'],sizes:['S','M','L','XL','2XL']}];
let cart=JSON.parse(localStorage.getItem('jf_cart'))||[],orders=JSON.parse(localStorage.getItem('jf_orders'))||[];
function save(){localStorage.setItem('jf_products',JSON.stringify(products));localStorage.setItem('jf_cart',JSON.stringify(cart));localStorage.setItem('jf_orders',JSON.stringify(orders))}
function renderProducts(){const d=document.getElementById('products');d.innerHTML='';products.forEach(p=>{const image=p.image||'https://placehold.co/800x800/111111/ffffff?text='+encodeURIComponent(p.name);d.innerHTML+=`<div class="product"><img src="${image}" alt="${p.name}"><div class="product-info"><h3>${p.name}</h3><strong>R${p.price}</strong></div><div class="colors">${p.colors.map((c,i)=>`<div class="color-dot ${i===0?'active':''}" style="background:${c.toLowerCase()}" title="${c}" onclick="selectColor(this)"></div>`).join('')}</div><div class="sizes">${p.sizes.map((s,i)=>`<div class="size ${i===0?'active':''}" onclick="selectSize(this)">${s}</div>`).join('')}</div><button class="add" onclick="addToCart(${p.id},this)">ADD TO BAG</button></div>`})}
function selectColor(e){e.parentElement.querySelectorAll('.color-dot').forEach(x=>x.classList.remove('active'));e.classList.add('active')}
function selectSize(e){e.parentElement.querySelectorAll('.size').forEach(x=>x.classList.remove('active'));e.classList.add('active')}
function addToCart(id,b){const card=b.closest('.product'),p=products.find(x=>x.id==id);cart.push({id:Date.now(),name:p.name,price:p.price,color:card.querySelector('.color-dot.active')?.title||'Default',size:card.querySelector('.size.active')?.innerText||'M',qty:1});save();updateCart();toggleCart()}
function updateCart(){document.getElementById('cartCount').innerText=cart.length;let t=0,h='';cart.forEach((c,i)=>{t+=c.price*c.qty;h+=`<div style="display:flex;justify-content:space-between;gap:12px;margin:12px 0;padding-bottom:12px;border-bottom:1px solid #222"><div>${c.name}<br><small>${c.color} / ${c.size} × ${c.qty}</small></div><div><button onclick="changeQty(${i},-1)">−</button> <button onclick="changeQty(${i},1)">+</button> <button onclick="removeItem(${i})">✕</button></div></div>`});document.getElementById('cartItems').innerHTML=h||'Empty bag';document.getElementById('cartTotal').innerText='R'+t}
function changeQty(i,d){cart[i].qty+=d;if(cart[i].qty<1)cart.splice(i,1);save();updateCart()}function removeItem(i){cart.splice(i,1);save();updateCart()}function toggleCart(){document.getElementById('cart').classList.toggle('open')}function toggleAdmin(){document.getElementById('admin').classList.toggle('open')}
function loginAdmin(){if(document.getElementById('adminPass').value==='jforges2026'){document.getElementById('adminLogin').style.display='none';document.getElementById('adminPanel').style.display='block';renderOrders()}else alert('Wrong password')}
function addProduct(){const name=document.getElementById('pName').value.trim(),price=parseInt(document.getElementById('pPrice').value),image=document.getElementById('pImage').value.trim(),colors=document.getElementById('pColors').value.split(',').map(s=>s.trim()).filter(Boolean),sizes=document.getElementById('pSizes').value.split(',').map(s=>s.trim()).filter(Boolean);if(!name||!price)return alert('Name + Price needed');products.push({id:Date.now(),name,price,image,colors:colors.length?colors:['Black'],sizes:sizes.length?sizes:['M','L']});save();renderProducts();alert('Added!')}
function placeOrder(){const name=document.getElementById('cName').value.trim(),phone=document.getElementById('cPhone').value.trim(),address=document.getElementById('cAddress').value.trim(),city=document.getElementById('cCity').value.trim();if(!name||!phone||!address||!city||!cart.length)return alert('Fill in all delivery info and add items');const total=cart.reduce((a,b)=>a+b.price*b.qty,0),lines=cart.map(c=>`- ${c.name} (${c.color}/${c.size}) x${c.qty} - R${c.price*c.qty}`).join('\n'),message=`NEW ORDER — JF FORGES\nName: ${name}\nWhatsApp: ${phone}\nAddress: ${address}, ${city}\nItems:\n${lines}\nTOTAL: R${total}`;orders.push({name,phone,address,city,cart:[...cart],total,date:new Date().toLocaleString()});save();const yourNumber='277XXXXXXXXX';if(yourNumber.includes('X'))return alert('Order saved. Replace the WhatsApp number in script.js with your real number.');window.open(`https://wa.me/${yourNumber}?text=${encodeURIComponent(message)}`,'_blank');cart=[];save();updateCart()}
function renderOrders(){document.getElementById('ordersList').innerHTML=orders.map(o=>`<div style="border:1px solid #222;padding:8px;margin-bottom:8px"><b>${o.name}</b> — ${o.phone}<br>R${o.total} — ${o.date}</div>`).join('')||'No orders yet'}
function clearOrders(){if(confirm('Clear all orders?')){orders=[];save();renderOrders()}}
renderProducts();updateCart();