create extension if not exists pgcrypto;
create table if not exists public.profiles(id uuid primary key references auth.users(id) on delete cascade, role text not null default 'customer');
create table if not exists public.products(id text primary key, name text not null, description text default '', category text default 'JF', badge text default 'JF', colors jsonb not null default '[]', sizes jsonb not null default '[]', prices jsonb not null default '{}', images jsonb not null default '[]', sort_order integer not null default 0, created_at timestamptz not null default now());
create table if not exists public.orders(id text primary key, name text, email text, phone text, address text, city text, province text, country text, note text, total numeric, items jsonb, method text, created_at timestamptz not null default now());
create table if not exists public.store_settings(key text primary key,value text not null);
insert into public.store_settings(key,value) values ('title','JF ESSENTIALS'),('wa',''),('email','') on conflict(key) do nothing;
create or replace function public.is_admin() returns boolean language sql stable security definer set search_path=public as $$ select exists(select 1 from public.profiles where id=auth.uid() and role='admin'); $$;
alter table public.profiles enable row level security;
alter table public.products enable row level security;
alter table public.orders enable row level security;
alter table public.store_settings enable row level security;
drop policy if exists profiles_self_read on public.profiles;
create policy profiles_self_read on public.profiles for select using (id=auth.uid() or public.is_admin());
drop policy if exists products_public_read on public.products;
create policy products_public_read on public.products for select using (true);
drop policy if exists products_admin_write on public.products;
create policy products_admin_write on public.products for all using (public.is_admin()) with check (public.is_admin());
drop policy if exists orders_admin_all on public.orders;
create policy orders_admin_all on public.orders for all using (public.is_admin()) with check (public.is_admin());
drop policy if exists orders_public_insert on public.orders;
create policy orders_public_insert on public.orders for insert with check (true);
drop policy if exists settings_public_read on public.store_settings;
create policy settings_public_read on public.store_settings for select using (true);
drop policy if exists settings_admin_write on public.store_settings;
create policy settings_admin_write on public.store_settings for all using (public.is_admin()) with check (public.is_admin());
insert into storage.buckets(id,name,public) values ('product-images','product-images',true) on conflict(id) do nothing;
drop policy if exists product_images_public_read on storage.objects;
create policy product_images_public_read on storage.objects for select using (bucket_id='product-images');
drop policy if exists product_images_admin_insert on storage.objects;
create policy product_images_admin_insert on storage.objects for insert with check (bucket_id='product-images' and public.is_admin());
drop policy if exists product_images_admin_delete on storage.objects;
create policy product_images_admin_delete on storage.objects for delete using (bucket_id='product-images' and public.is_admin());
-- After creating your Supabase Auth user, get its UUID and run:
-- insert into public.profiles(id,role) values ('YOUR-USER-UUID','admin') on conflict(id) do update set role='admin';
